//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("APPOINTMENTS")]
    public partial class APPOINTMENT : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        public APPOINTMENT()
        {
            this.APPOINTMENTFOLLOWUPS = new List<APPOINTMENTFOLLOWUP>();
            this.APPOINTMENTMESSAGES = new List<APPOINTMENTMESSAGE>();
            this.APPOINTMENTRATINGS = new List<APPOINTMENTRATING>();
            this.APPOINTMENTSLOTS = new List<APPOINTMENTSLOT>();
            this.CANCELLEDAPPOINTMENTS = new List<CANCELLEDAPPOINTMENT>();
        }

        [Key]
        public long APPOINTMENTID { get; set; }

        public string DOCTORID { get; set; }

        [ForeignKey("PATIENTID")]
        public virtual USERSINFORMATION USERSINFORMATION { get; set; }
        public string PATIENTID { get; set; }

        public string STATUS { get; set; }
        public string ISEXISITING { get; set; }
        public DateTime BOOKEDON { get; set; }
        public string REASONFORVISIT { get; set; }
        public Nullable<DateTime> APPOINTMENTSTARTTIME { get; set; }
        public Nullable<DateTime> APPOINTMENTENDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime DateCreated { get; set; }
         public string MODIFIEDBY{ get; set; }
        public Nullable<DateTime> MODIFIEDON { get; set; }
        public Nullable<long> STATUSID { get; set; }
        public Nullable<long> PAYMENTSTATUSID { get; set; }
        public string PAYKEY { get; set; }
        public Nullable<decimal> PAYAMOUNT { get; set; }
        public Nullable<decimal> REFUNDAMOUNT { get; set; }
        public string PROVIDERINITIALS { get; set; }       
        public Nullable<long> CHATSESSIONID { get; set; }

        public string VIDEOSESSIONID { get; set; }
        public bool? ISVIDEOACTIVE { get; set; }
        public int? LAPSEDMINUTES { get; set; }
        public bool? SHOWTIMER { get; set; }

         [NotMapped]
        public string tabindex { get; set; }

        

        public long DOCTORSLOTID { get; set; }

        [Display(Name = "I give the permission for the provider to see my Health History:")]
        public bool uploadreport { get; set; }

        [Display(Name = "I certify that I have read and accept the Terms of Use From Doc On Video:")]
        public bool termsOfUse { get; set; }

        [Display(Name = " I have read and accept the Release Statements:")]
        public bool realeaseStatement { get; set; }

        [Display(Name = " Your Initials:")]
        public string patientintials { get; set; }

        [Display(Name = "I give permission for that I will not give treatment:")]
        public bool medicaladviceDoctor { get; set; }

        [Display(Name = "I certify that I have read and accept the Terms of Use From Doc On Video:")]
        public bool termsOfUseDoctor { get; set; }

        [Display(Name = " I have read and accept the Release Statements:")]
        public bool releaseStatementDoctor { get; set; }

        [Display(Name = " Your Initials:")]
        public string doctorintials { get; set; }
    
        public virtual ICollection<APPOINTMENTFOLLOWUP> APPOINTMENTFOLLOWUPS { get; set; }
        public virtual ICollection<APPOINTMENTMESSAGE> APPOINTMENTMESSAGES { get; set; }
        public virtual ICollection<APPOINTMENTRATING> APPOINTMENTRATINGS { get; set; }
        public virtual ICollection<APPOINTMENTSLOT> APPOINTMENTSLOTS { get; set; }
        public virtual ICollection<CANCELLEDAPPOINTMENT> CANCELLEDAPPOINTMENTS { get; set; }
    }
}
