//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("APPOINTMENTRATINGS")]
    public partial class APPOINTMENTRATING : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        [Key]
        public long APPOINTMENTRATINGID { get; set; }

        [NotMapped]
        public string FIRSTNAME { get; set; }

        [NotMapped]
        public string LASTNAME { get; set; }

        [Display(Name = "Doctor On Time")]
        public string DOCTORONTIME { get; set; }

        [Display(Name = "Comment")]
        [StringLength(1000, ErrorMessage = "Maximum 1000 characters.")]
        public string COMMENT { get; set; }

        [Display(Name = "Client Rating")]
        public Nullable<decimal> CLIENTRATING { get; set; }
        public Nullable<decimal> DOCTORRATING { get; set; }
        public Nullable<DateTime> RATINGDATE { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime DateCreated { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<DateTime> MODIFIEDON { get; set; }

        [NotMapped]
        [MaxLength(200)]
        public string LOGINNANE { get; set; }

        [NotMapped]
        [MaxLength(256)]
        public string USERPHOTOFILEPATH { get; set; }

        

        [ForeignKey("APPOINTMENTID")]
        public virtual APPOINTMENT APPOINTMENT { get; set; }
        public long APPOINTMENTID { get; set; }
    }
}
