//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("ATTACHMENTLINKS")]
    public partial class ATTACHMENTLINK : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        [Key]      
        public long ATTACHMENTLINKID { get; set; }
        public string LINKTYPE { get; set; }
       
        public long LINKTYPEID { get; set; }

        [ForeignKey("ATTACHMENTID")]
        public virtual DOCUMENTATTACHMENT DOCUMENTATTACHMENT { get; set; }
        public long ATTACHMENTID { get; set; }
    }
}
