//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("CHATMESSAGES")]
    public partial class CHATMESSAGE : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        public CHATMESSAGE()
        {
        }

        [Key]
        public Int64 MESSAGEID { get; set; }
        
        [MaxLength(50)]
        public string DOCTORID { get; set; }

        [MaxLength(50)]
        public string PATIENTID { get; set; }

        public string CHATTEXT { get; set; }

        public DateTime TIMESTAMP { get; set; }

        [MaxLength(50)]
        public string COLOR { get; set; }

        [MaxLength(50)]
        public string MESSAGEFROM { get; set; }

        [NotMapped]
        public DateTime StartTime { get; set; }

        [NotMapped]
        public DateTime EndTime { get; set; }

       
        public long APPOINTMENTID { get; set; }
        
    }
}
