//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("CHATSESSIONS")]
    public partial class CHATSESSION : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        public CHATSESSION()
        {
            this.CHATHISTORIES = new HashSet<CHATHISTORY>();
        }
        [Key]
        public long CHATSESSIONID { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string ROOMCODE { get; set; }
        public Nullable<int> DURATION { get; set; }
        public string ROOMSTATUS { get; set; }
        public Nullable<DateTime> STARTTIME { get; set; }
    
        public virtual ICollection<CHATHISTORY> CHATHISTORIES { get; set; }
    }
}
