//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("DOCPAYMENTS")]
    public partial class DOCPAYMENT : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        public DOCPAYMENT()
        {
        }

         [Key]
         public Int64 DOCPAYMENTID { get; set; }
         public DateTime PAYMENTREQUESTDATE { get; set; }
         public string FEESPAYER { get; set; }
         public string SENDEREMAIL { get; set; }
         public string VERIFYSIGN { get; set; }
         public string TESTIPN { get; set; }
         public string TRANSACTIONIDFORSENDERTXN { get; set; }
         public string TRANSACTIONRECEIVER { get; set; }
         public string TRANSACTIONISPRIMARYRECEIVER { get; set; }
         public string PAYKEY { get; set; }
         public string ACTIONTYPE { get; set; }
         public string TRANSACTIONID { get; set; }
         public string TRANSACTIONSTATUS { get; set; }
         public string TRANSACTIONPAYMENTTYPE { get; set; }
         public string TRANSACTIONSTATUSFORSENDERTXN { get; set; }
         public string TRANSACTIONPENDINGREASON { get; set; }
         public string TRANSACTIONTYPE { get; set; }
         public decimal TRANSACTIONAMOUNT { get; set; }
         public string REVERSEALLPARALLELPAYMENTSONERROR { get; set; }
         public DateTime STARTDATE { get; set; }
         public DateTime ENDDATE { get; set; }
         public string CURRENCYCODE { get; set; }
         public Double MAXAMOUNTPERPAYMENT { get; set; }
         public int MAXNUMBEROFPAYMENTSPERPERIOD { get; set; }
         public int MAXTOTALAMOUNTOFALLPAYMENTS { get; set; }
         public string STATUS { get; set; }
         public DateTime DateCreated { get; set; }
         public DateTime MODIFIEDON { get; set; }
         public string CREATEDBY { get; set; }
         public string MODIFIEDBY { get; set; }
         public string ERRORDETAILS { get; set; }
        [ForeignKey("UserName")]
        public virtual USERSINFORMATION USERSINFORMATIONS { get; set; }
        public string UserName { get; set; }

    }
}
