//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

     [Table("DOCTORSINFORMATIONS")]
    public partial class DOCTORSINFORMATION : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        [Key]      
        public int DOCTORID { get; set; }
        public string PRACTICENAME { get; set; }
        public string SUFFIX { get; set; }
        public string LICENSE { get; set; }
        public string STATELICENSE { get; set; }
        public Nullable<DateTime> PRACTISESINCE { get; set; }
        public string ABOUTME { get; set; }
        public string WEBSITE { get; set; }
        public string PRESCRIBEELECTRONICALLY { get; set; }
        public string PAYPALID { get; set; }
        public string ISSUBSCRIBED { get; set; }
        public Nullable<DateTime> LICENSEEXPIRESON { get; set; }
        public string PAYPALEMAIL { get; set; }
        public string MEDICALSCHOOL { get; set; }
        public string EDUCATIONALQUAL { get; set; }
        public string AWARDCERTIFICATION { get; set; }
        public string RESIDENCY { get; set; }
        public string HOSPITALAFFILIATION { get; set; }
        public string LICENSEDIN { get; set; }
        public string CERTIFICATIONBOARD { get; set; }
        public string PROFESSIONALMEMBERSHIP { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime DateCreated { get; set; }
         public string MODIFIEDBY{ get; set; }

        [ForeignKey("UserName")]
        public virtual USERSINFORMATION USERSINFORMATIONS { get; set; }
        public string UserName { get; set; }
        public Nullable<DateTime> MODIFIEDON { get; set; }

    }
}
