//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("DOCTORSLOTS")]
    public partial class DOCTORSLOT : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        [Key]
        public long DOCTORSLOTID { get; set; }
       
        
        public int CALYEAR { get; set; }
        public int CALMONTH { get; set; }
        public int CALDATE { get; set; }
        public DateTime FROMTIME { get; set; }
        public DateTime TOTIME { get; set; }
        public string AVAILABILITYMODE { get; set; }
        public string TIMEZONE { get; set; }
        public decimal? PAYRATE { get; set; }
        public string STATUS { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime DateCreated { get; set; }
         public string MODIFIEDBY{ get; set; }
        public Nullable<DateTime> MODIFIEDON { get; set; }
        public Nullable<DateTime> SLOTDATE { get; set; }

        //[ForeignKey("AVAILABILITYID")]
        //public virtual DOCTORAVAILABILITY DOCTORAVAILABILITY { get; set; }
        //public Nullable<long> AVAILABILITYID { get; set; }

        [ForeignKey("UserName")]
        public virtual USERSINFORMATION USERSINFORMATIONS { get; set; }
        public string UserName { get; set; }

        [NotMapped]
        public double TimeZoneOffset  { get; set; }

        [NotMapped]
        public int DSTObserved { get; set; }
    }
}
