//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("DOCTORWORKINGINSTITUIONS")]
    public partial class DOCTORWORKINGINSTITUION : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }
         [Key]
        public long WORKINGINSTITUIONID { get; set; }


        
         public string CLINICZIPCODE { get; set; }
         [Display(Name = "Clinic State")]
         public string CLINICUSERSTATE { get; set; }

         [Display(Name = "Clinic City")]
         public string CLINICCITY { get; set; }

         [Display(Name = "Street Address 1")]
         [MaxLength(250)]
         public string STREETADDRESS1 { get; set; }

        
         public string MAPPINGADDRESS { get; set; }
         public string ABOUTCLINIC { get; set; }
         [Display(Name = "Street Address 2")]
         [MaxLength(250)]
         public string STREETADDRESS2 { get; set; }
         public string CONTACTPERSON { get; set; }
         public string CONTACTMAILID { get; set; }
        public string TELEPHONE { get; set; }
        public string INSTITUTIONNAME { get; set; }
        public string INSTITUTIONIMAGEPATH { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime DateCreated { get; set; }
         public string MODIFIEDBY{ get; set; }
        public Nullable<DateTime> MODIFIEDON { get; set; }
       

        [ForeignKey("UserName")]
        public virtual USERSINFORMATION USERSINFORMATIONS { get; set; }
        public string UserName { get; set; }

       
    }
}
