//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("DOCUMENTATTACHMENTS")]
    public partial class DOCUMENTATTACHMENT : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        public DOCUMENTATTACHMENT()
        {
            this.ATTACHMENTLINKS = new HashSet<ATTACHMENTLINK>();
        }

         [Key]
        public long ATTACHMENTID { get; set; }
        public byte[] ATTACHMENT { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime DateCreated { get; set; }
         public string MODIFIEDBY{ get; set; }
        public Nullable<DateTime> MODIFIEDON { get; set; }
        public string FILENAME { get; set; }
    
        public virtual ICollection<ATTACHMENTLINK> ATTACHMENTLINKS { get; set; }
    }
}
