//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("MESSAGES")]
    public partial class MESSAGE : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        public MESSAGE()
        {
            this.APPOINTMENTMESSAGES = new HashSet<APPOINTMENTMESSAGE>();
        }

        [Key]
        public long MESSAGEID { get; set; }
      
     
        public DateTime SENDDATE { get; set; }
       
     
        public string MESSAGETYPE { get; set; }
        public string MESSAGESTATUS { get; set; }
        public string SENDBY { get; set; }

        [Display(Name = "To")]
        public string SENDMESSAGETO { get; set; }
        [Display(Name = "Subject")]
        public string MESSAGESUBJECT { get; set; }
        [Display(Name = "Body")]
        [StringLength(1000, ErrorMessage = "Maximum 1000 characters.")]
        public string MESSAGEBODY { get; set; }
       
        public string SENDMESSAGEFROM { get; set; }
        public string SENDMESSAGEBCC { get; set; }
        public string SENDMESSAGECC { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime DateCreated { get; set; }
         public string MODIFIEDBY{ get; set; }
        public Nullable<DateTime> MODIFIEDON { get; set; }
        public string MESSAGESTATUSFROM { get; set; }
        public string MESSAGESTATUSTO { get; set; }

       
          [NotMapped]
        [MaxLength(200)]
        public string LOGINNANE { get; set; }

          [NotMapped]
        [MaxLength(256)]
        public string USERPHOTOFILEPATH { get; set; }

        [NotMapped]
        [Display(Name = "Provider Type:")]
        public string ProviderType { get; set; }


        [NotMapped]
        [Display(Name = "Gender:")]
        [MaxLength(10)]
        public string SearchGender { get; set; }

        [NotMapped]
        [Display(Name = "ZIP code:")]
        [MaxLength(6)]
        public string SEARCHZIPCODE { get; set; }
    
        public virtual ICollection<APPOINTMENTMESSAGE> APPOINTMENTMESSAGES { get; set; }
    }
}
