//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("PROCEDURES")]
    public partial class PROCEDURE : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        public PROCEDURE()
        {

        }

        [Key]
        public int PROCEDUREID { get; set; }

        [Display(Name = "PROCEDURE REPORTNAME")]
        [MaxLength(100)]
        public string PROCEDUREREPORTNAME { get; set; }

        public Nullable<DateTime> PROCEDUREDATE { get; set; }

        [Display(Name = "PROCEDURE NOTES")]
        [MaxLength(700)]
        public string PROCEDURENOTES { get; set; }

        [Display(Name = "Comment")]
        public string COMMENT { get; set; }

        public string CREATEDBY { get; set; }

        public DateTime DateCreated { get; set; }

        public string MODIFIEDBY { get; set; }

       public string REPORTSTATUS { get; set; }

        public Nullable<DateTime> MODIFIEDON { get; set; }


        [NotMapped]
        [MaxLength(200)]
        public string LOGINNANE { get; set; }

        [NotMapped]
        [MaxLength(256)]
        public string USERPHOTOFILEPATH { get; set; }

        [NotMapped]
        [Display(Name = "Provider Type:")]
        public string ProviderType { get; set; }


        [NotMapped]
        [Display(Name = "Gender:")]
        [MaxLength(10)]
        public string SearchGender { get; set; }

        [NotMapped]
        [Display(Name = "ZIP code:")]
        [MaxLength(6)]
        public string SEARCHZIPCODE { get; set; }


        [ForeignKey("UserName")]
        public virtual USERSINFORMATION USERSINFORMATIONS { get; set; }
        public string UserName { get; set; }




    }
}