//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("SECURITIES")]
    public partial class SECURITY : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

         [Key]
        public long SECURITYID { get; set; }
        public string MODULENAME { get; set; }
        public string ACTIONNAME { get; set; }
        public string ISALLOWED { get; set; }
    }
}
