//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("SUBSCRIPTIONINSTALLMENTS")]
    public partial class SUBSCRIPTIONINSTALLMENT : IObjectWithState
    {
        [NotMapped]
        public State State { get; set; }

        [Key]
        public long INSTALLMENTID { get; set; }
       
        public string PAYPALSUBSCRIPTIONID { get; set; }
        public string RECEIVEREMAIL { get; set; }
        public string RECEIVERID { get; set; }
        public string PAYMENTSTATUS { get; set; }
        public string TXNTYPE { get; set; }
        public string TXNID { get; set; }
        public Nullable<DateTime> PAYMENTDATE { get; set; }
        public string IPNTRACKID { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string PAYEREMAIL { get; set; }
        public string PAYERID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<DateTime> DateCreated { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<DateTime> MODIFIEDON { get; set; }
         public string MODIFIEDBY{ get; set; }
        public string PENDINGREASON { get; set; }
        public string PAYMENTTYPE { get; set; }
        public string ERRORDETAILS { get; set; }

        [ForeignKey("SUBSCRIPTIONID")]
        public virtual SUBSCRIPTION SUBSCRIPTION { get; set; }
        public Nullable<long> SUBSCRIPTIONID { get; set; }
    }
}
