//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCVIDEO.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DOCVIDEO.ObjectState;

    [Table("USERSLANGUAGES")]
    public partial class USERSLANGUAGE : IObjectWithState
    {
        public USERSLANGUAGE()
        {
          
        }
        [Key]
        [Column ("USERLANGUAGEID")]
        public long USERLANGUAGEID { get; set; }
      

        
     
        public string CREATEDBY { get; set; }
        public DateTime DateCreated { get; set; }
        public string MODIFIEDBY{ get; set; }
        public Nullable<DateTime> MODIFIEDON { get; set; }
       

        [ForeignKey("LANGUAGEKEYID")]
        public virtual LANGUAGE LANGUAGE { get; set; }
        public string LANGUAGEKEYID { get; set; }

        [ForeignKey("UserName")]
        public virtual USERSINFORMATION USERSINFORMATION { get; set; }
        public string UserName { get; set; }

        [NotMapped]
        public State State { get; set; }
    }
}
